### ISSUE TITLE
Initial broad implementation questions

### ISSUE THREAD

**Issue by subversive-owl** [ratpoison-io/rust-clblas#1]
Here are some questions I am thinking about:

- Use rust [ocl](https://github.com/cogciprocate/ocl), or re-implement own approach?
- Target the [BLAS routines](https://github.com/CNugteren/CLBlast#supported-routines) verbatim, or directly abstract to higher, more rust-idiomatic operations (where applicable)?

**Comment by drahnr** [comment]
I tried ocl and it is a great library and initially I thought about using it for ocl. But given there is already an abstraction and the fact that we would not gain much from the ocl extra features made me question that again. https://github.com/ratpoison-io/collenchyma/tree/master/src/frameworks/opencl
It also has seen some serious work in the last 12 months and there were a few breaking points.

If we provide the blas operations on tensor level, they can be a drop in replacement without (much) further work on leaf/collenchyma :) thus I would suggest to start from there.

**Comment by drahnr** [comment]
Maybe this whole project is unnecessary and this is better suited to be implemented as part of ratpoison-io/collenchmya-blas

**Comment by subversive-owl** [comment]
I'll take a look at those, thanks

**Comment by subversive-owl** [comment]
I'll take a look at those, thanks!

**Comment by subversive-owl** [comment]
I agree, I think the blas implementations are better kept together.
